### PR TITLE
Resolve nested criteria match issue

### PR DESCRIPTION
**Pull request by hani-iterable**
## 🔹 Jira Ticket(s)

* [MOB-9309](https://iterable.atlassian.net/browse/MOB-9309)

## ✏️ Description

> Resolve issue for nested object criteria match.

## Test Step

> Go to AUTTesting and try to match criteria which has '.' in field. like (saved_cars.color)

[MOB-9309]: https://iterable.atlassian.net/browse/MOB-9309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by evantk91** [comment]
@hani-iterable Can you add support for nested objects in the data fields? Seems like this is not supported.

**Comment by hani-iterable** [comment]
@evantk91 It is not possible the nested object are coming from criteria as iterable portal is not allowing you to add so. If you want to do so, can you please provide me an example for your expectation?

**Comment by evantk91** [comment]
> @evantk91 It is not possible the nested object are coming from criteria as iterable portal is not allowing you to add so. If you want to do so, can you please provide me an example for your expectation?

Please see the attached ticket. When a nested data field is provided for the user, the associated criteria is not matching.

**Review by evantk91 — APPROVED** [review]
Verified for situation of nested data field listed on the ticket.

**Pull request merged**
