### PR TITLE
[MOB-1371] rename Const to C

### PR DESCRIPTION
**Pull request by roninopf**

### CODE REVIEW

**Comment by tapashmajumder** [comment]
Const is a meaningful name and the intent is clear. Not sure why we are renaming Const to C. I think we should close this PR.

**Comment by roninopf** [comment]
I feel like it's actually clearer, and syntactically easier to manage. My inspiration was from Android like in this example code: https://developer.android.com/guide/topics/resources/providing-resources#fromCodeUses

**Comment by tapashmajumder** [comment]
On the other hand iOS encourages meaningful names even if they are long. I don’t think C is more descriptive than Const.

**Comment by Ayyanchira** [comment]
uhm.. that android example might be misleading because that`R` is kind of an exceptional case. It's a part of Android to link the code with Resources like strings, layouts etc.

**Comment by vbabenkoru** [comment]
Yeah, I agree.. `R` in Android is auto-generated from resources, and is not defined manually. iOS doesn't have a similar convention, so it may be less clear.

**Comment by roninopf** [comment]
Haha alright, will close.

**Pull request closed without merging**
