### PR TITLE
[MOB-7458] - Aligning iOS with Android

### PR DESCRIPTION
**Pull request by Ayyanchira**
## 🔹 Jira Ticket(s)

* [MOB-7458](https://iterable.atlassian.net/browse/MOB-7458)

## ✏️ Description

Config object
Enum for type
Removal of ViewDelegate and its methods

[MOB-7458]: https://iterable.atlassian.net/browse/MOB-7458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by evantk91 — APPROVED** [review]
LGTM at least for today's bug bash.

A few points we need to address before release:

- notification default is not aligned with Android. The background and border colors differ from the card and banner styles.
- the second button is defaulting to this weird block button. it should be a button with a transparent background and the same color text as the first button. See the figma.
- the second button background and border color should be configurable. I will add this to the android side.
- the card view type should collapse when the image is not provided to align with the android side and the discussion I had with design (stephanie)

**Comment by Ayyanchira** [comment]
Will bug bash with this branch so we can work on this before merging into embedded

**Comment by evantk91** [comment]
> LGTM at least for today's bug bash.
> 
> A few points we need to address before release:
> 
> * notification default is not aligned with Android. The background and border colors differ from the card and banner styles.
> * the second button is defaulting to this weird block button. it should be a button with a transparent background and the same color text as the first button. See the figma.
> * the second button background and border color should be configurable. I will add this to the android side.
> * the card view type should collapse when the image is not provided to align with the android side and the discussion I had with design (stephanie)

* point 2 addressed

**Review by evantk91 — APPROVED** [review]
LGTM. merging with base feature branch.

**Pull request merged**
