### PR TITLE
[MOB-4275] - Mac Catalyst support

### PR DESCRIPTION
**Pull request by tapashmajumder**
## 🔹 Jira Ticket(s)

* [MOB-4275](https://iterable.atlassian.net/browse/MOB-4275)

## ✏️ Description

> Add support for Mac Catalyst

### CODE REVIEW

**Comment by LeadAssimilator** [comment]
The [scripts/create-xcframework-zips.sh](https://github.com/Iterable/swift-sdk/pull/539/commits/0f7c043a1a2034b2766619e7efa0e3ab78aebaba#diff-7e75e7c796870067857bddf7c71fc3e7b6da7c8299f57f84c40d3b7584ecb246) are missing...

**Comment by teamplayon** [comment]
The [scripts/create-xcframework-zips.sh ](https://github.com/Iterable/swift-sdk/pull/539/files#diff-7e75e7c796870067857bddf7c71fc3e7b6da7c8299f57f84c40d3b7584ecb246) changes are missing...

**Comment by teamplayon** [comment]
The scripts/create-xcframework-zips.sh needs updated for proper mac catalyst support otherwise the compiled xcframework will not contain the mac catalyst build.

Also, we've force pushed some additional minor changes to the script so switch to bash, emit the exact command that failed and fixed some inconsistencies in quotes and destination specifications.

**Review by roninopf — APPROVED** [review]

**Comment by tapashmajumder** [comment]
Hi @teamplayon Thank you so much for your PR. It is *extremely helpful*.

We have created a separate branch and PR for your script changes.

We have split that up your PR into separate ones. This helps us keep PRs isolated. Also, it helps us to make minor changes. We are in the process of merging all your changes with minor or no changes.

**Pull request merged**
